cuda_visible_devices: "0,1,2,3,4,5,6,7"
base_model_id: "mistralai/Mixtral-8x7B-Instruct-v0.1"
retriever:
  top_k: 15

reranker:
  top_n: 3
  min_score: 7

paper_dir: "paper_jsons"
paper_file: "Breaking_LTE.json"
colname: "breaking_lte"
